version: '3'
services:
  PostgreSQL:

    image: postgres
    restart: always
    container_name: PostgreSQL
    environment:

      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "15432:5432"


