version: '3'
services:
  PostgreSQL:

    image: postgres
    restart: always
    container_name: PostgreSQL
    environment:
      POSTGRES_USER: bityta
      POSTGRES_PASSWORD: 380201
    ports:
      - "15432:5432"
#    volumes:



  app:
    build: ./
    container_name: java_app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    depends_on:
      - PostgreSQL

#    volumes:
#      - ./data:/var/lib/postgresql/data